spring:
  mvc:
    view:
      prefix: '/WEB-INF/view/'
      suffix: '.jsp'

test.property: 'test'

shop.properties.products:
  - product:
    id: 1
    title: 'Phone'
    cost: 500
  - product:
    id: 2
    title: 'Phone2'
    cost: 600
  - product:
    id: 3
    title: 'Phone3'
    cost: 550

products:
  product: